language: node_js

os:
  - linux

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"
  - "9"

cache: yarn

script:
  - yarn
  - yarn lint

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload